sonar.projectKey=Moustansir-H_TP2
sonar.organization=moustansir-h

sonar.sources=auth/src/main
sonar.tests=auth/src/test
sonar.test.inclusions=auth/src/test/**/*.java
sonar.java.binaries=auth/target/classes
sonar.java.libraries=auth/target/dependency/*
sonar.coverage.jacoco.xmlReportPaths=auth/target/site/jacoco/jacoco.xml
