sonar.projectKey=Moustansir-H_TP2
sonar.organization=moustansir-h

# Dossier source contenant le code Java
sonar.sources=auth

# Dossier contenant les fichiers compilés (.class)
sonar.java.binaries=auth/target/classes

# (Optionnel) Exclure le front-end
sonar.exclusions=auth-front/**/*,node_modules/**/*